2025-06-10 12:31:22,640 INFO    MainThread:3668 [wandb_setup.py:_flush():81] Current SDK version is 0.20.1
2025-06-10 12:31:22,640 INFO    MainThread:3668 [wandb_setup.py:_flush():81] Configure stats pid to 3668
2025-06-10 12:31:22,640 INFO    MainThread:3668 [wandb_setup.py:_flush():81] Loading settings from C:\Users\ianco\.config\wandb\settings
2025-06-10 12:31:22,640 INFO    MainThread:3668 [wandb_setup.py:_flush():81] Loading settings from C:\Users\ianco\OneDrive - Nexus365\Code_C\btsp-rl-main\wandb\settings
2025-06-10 12:31:22,640 INFO    MainThread:3668 [wandb_setup.py:_flush():81] Loading settings from environment variables
2025-06-10 12:31:22,641 INFO    MainThread:3668 [wandb_init.py:setup_run_log_directory():703] Logging user logs to C:\Users\ianco\OneDrive - Nexus365\Code_C\btsp-rl-main\wandb\run-20250610_123122-jfh1nv1o\logs\debug.log
2025-06-10 12:31:22,641 INFO    MainThread:3668 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to C:\Users\ianco\OneDrive - Nexus365\Code_C\btsp-rl-main\wandb\run-20250610_123122-jfh1nv1o\logs\debug-internal.log
2025-06-10 12:31:22,641 INFO    MainThread:3668 [wandb_init.py:init():831] calling init triggers
2025-06-10 12:31:22,641 INFO    MainThread:3668 [wandb_init.py:init():836] wandb.init called with sweep_config: {}
config: {'env': {'width': 6, 'height': 6, 'walls': [[1, 1], [2, 1], [3, 1], [3, 2], [3, 3]], 'max_steps': 50, 'render_cell_size': 32}, 'agent': {'name': 'DQN', 'gamma': 0.99, 'lr': 0.001, 'batch_size': 64, 'min_replay': 1000, 'target_sync': 200, 'hidden_size': 64, 'buffer_capacity': 50000}, 'train': {'episodes': 5000, 'max_steps': 200, 'eps_start': 1.0, 'eps_end': 0.05, 'eps_decay': 0.995, 'eval_interval': 1000, 'seed': 10, 'render': False}, 'wandb': {'enabled': True, 'project': 'meta_BTSP_RL', 'entity': 'conehed', 'group': 'rlcone'}, '_wandb': {}}
2025-06-10 12:31:22,641 INFO    MainThread:3668 [wandb_init.py:init():872] starting backend
2025-06-10 12:31:22,968 INFO    MainThread:3668 [wandb_init.py:init():875] sending inform_init request
2025-06-10 12:31:23,093 INFO    MainThread:3668 [wandb_init.py:init():883] backend started and connected
2025-06-10 12:31:23,094 INFO    MainThread:3668 [wandb_init.py:init():956] updated telemetry
2025-06-10 12:31:23,095 INFO    MainThread:3668 [wandb_init.py:init():980] communicating run to backend with 90.0 second timeout
2025-06-10 12:31:26,618 INFO    MainThread:3668 [wandb_init.py:init():1032] starting run threads in backend
2025-06-10 12:31:26,674 INFO    MainThread:3668 [wandb_run.py:_console_start():2453] atexit reg
2025-06-10 12:31:26,674 INFO    MainThread:3668 [wandb_run.py:_redirect():2301] redirect: wrap_raw
2025-06-10 12:31:26,674 INFO    MainThread:3668 [wandb_run.py:_redirect():2370] Wrapping output streams.
2025-06-10 12:31:26,674 INFO    MainThread:3668 [wandb_run.py:_redirect():2393] Redirects installed.
2025-06-10 12:31:26,675 INFO    MainThread:3668 [wandb_init.py:init():1078] run started, returning control to user process
2025-06-10 12:31:26,675 INFO    MainThread:3668 [wandb_watch.py:_watch():70] Watching
2025-06-10 12:32:18,009 ERROR   asyncio_0 :3668 [util.py:get_module():252] [no run ID] Error importing optional module moviepy.video.io.ImageSequenceClip
Traceback (most recent call last):
  File "C:\Users\ianco\anaconda3\envs\dabal_meta_RL\Lib\site-packages\wandb\util.py", line 218, in import_module_lazy
    return sys.modules[name]
           ~~~~~~~~~~~^^^^^^
KeyError: 'moviepy.video.io.ImageSequenceClip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ianco\anaconda3\envs\dabal_meta_RL\Lib\site-packages\wandb\util.py", line 247, in get_module
    return import_module_lazy(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ianco\anaconda3\envs\dabal_meta_RL\Lib\site-packages\wandb\util.py", line 220, in import_module_lazy
    spec = importlib.util.find_spec(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib.util>", line 91, in find_spec
ModuleNotFoundError: No module named 'moviepy'
2025-06-10 12:32:18,722 INFO    MsgRouterThr:3668 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
